/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package libraryapp;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static libraryapp.DB_Connection.conn;

/**
 *
 * @author Shravya
 */
public class delete extends javax.swing.JFrame {

    /**
     * Creates new form delete
     */
    public delete() {
        initComponents();
        BookId.setVisible(false);
        jLabel2.setVisible(false);
        AuthorName.setVisible(false);
        jLabel4.setVisible(false);
        BranchIdNo.setVisible(false);
        cardno.setVisible(false);
        jLabel5.setVisible(false);
        jLabel9.setVisible(false);
                                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        BranchIdNo = new javax.swing.JTextField();
        AuthorName = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        BookId = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        cardno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Branch_id");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Author Name");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Book_id");

        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Reset.setText("RESET");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        BookId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookIdActionPerformed(evt);
            }
        });

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("SELECT ANY OPTION");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Book", "Authors", "LibraryBranch", "BookCopies", "Membership" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("Card Number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel5))
                                    .addGap(34, 34, 34)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BranchIdNo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cardno, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BookId, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(Submit)
                                    .addGap(40, 40, 40)))
                            .addGap(22, 22, 22)
                            .addComponent(Reset)
                            .addGap(49, 49, 49)
                            .addComponent(Back)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(586, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BookId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(BranchIdNo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cardno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit)
                    .addComponent(Reset)
                    .addComponent(Back))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        try
        {
            // Create a connection to the local MySQL server, with the "world" database selected.
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/librarynew?user=root&password=shravya92");
            // Create a SQL statement object and execute the query.
            Statement stmt = conn.createStatement();
            String name=jComboBox1.getSelectedItem().toString();
            switch(flag)
            {
                case 0:
                JOptionPane.showMessageDialog(null,"Please choose a option");
                case 1:
                String bid=BookId.getText();
                String add= "delete from book where book_id='"+bid+"';";
                stmt.executeUpdate(add);
                JOptionPane.showMessageDialog(null,"Succesfull");
                BookId.setText("");
                jComboBox1.setSelectedIndex(0);
                BookId.setVisible(false);
                jLabel2.setVisible(false);
                break;
                case 2:
                String bid1=BookId.getText();
                String an1=AuthorName.getText();
                String add1= "delete from Book_Authors where book_id='"+bid1+"' AND author_name='"+an1+"';";
                stmt.executeUpdate(add1);
                JOptionPane.showMessageDialog(null,"Succesfull");
                BookId.setText("");
                AuthorName.setText("");
                jComboBox1.setSelectedIndex(0);
                BookId.setVisible(false);
                AuthorName.setVisible(false);
                jLabel2.setVisible(false);
                jLabel4.setVisible(false);
                break;
                case 3:
                String bid2=BranchIdNo.getText();
                int b=Integer.parseInt(bid2);
                String add2= "delete from Library_Branch where branch_id="+b+";";
                stmt.executeUpdate(add2);
                JOptionPane.showMessageDialog(null,"Succesfull");
                BranchIdNo.setText("");
                jComboBox1.setSelectedIndex(0);
                BranchIdNo.setVisible(false);
                jLabel5.setVisible(false);
                break;
                case 4:
                String bid3=BranchIdNo.getText();
                int b1=Integer.parseInt(bid3);
                String bkid3=BookId.getText();
                String add3= "delete from book_copies where book_id='"+bkid3+"' AND branch_id="+b1+";";
                stmt.executeUpdate(add3);
                JOptionPane.showMessageDialog(null,"Succesfull");
                BranchIdNo.setText("");
                BookId.setText("");
                jComboBox1.setSelectedIndex(0);
                BranchIdNo.setVisible(false);
                BookId.setVisible(false);
                jLabel2.setVisible(false);
                jLabel5.setVisible(false);
                break;
            
                case 5:
                String cno=cardno.getText();
                String add6= "delete from Borrower where card_no='"+cno+"';";
                stmt.executeUpdate(add6);
                JOptionPane.showMessageDialog(null,"Succesfull");
                cardno.setText("");
                jComboBox1.setSelectedIndex(0);
                jLabel9.setVisible(false);
                break;
            }
                conn.close();
        
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_SubmitActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        switch(flag)
        {
            case 1:
            BookId.setText("");
            case 2:
            BookId.setText("");
            AuthorName.setText("");
            case 3:
            BranchIdNo.setText("");
            case 4:
            BranchIdNo.setText("");
            BookId.setText("");
            case 5:
            cardno.setText("");
         }
    }//GEN-LAST:event_ResetActionPerformed
public void close()
{
WindowEvent winclosingevent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclosingevent);
}
    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        close();
        HomePage hp=new HomePage();
        hp.setVisible(true);

    }//GEN-LAST:event_BackActionPerformed

    private void BookIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookIdActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:

        String name=jComboBox1.getSelectedItem().toString();

        if("".equals(name))
        {
            JOptionPane.showMessageDialog(null,"Please select any option");
        }

        else if("Book".equals(name))
        {
            //JOptionPane.showMessageDialog(null,"Enter Book_ID and Title");
            BookId.setVisible(true);
            jLabel2.setVisible(true);
            AuthorName.setVisible(false);
            jLabel4.setVisible(false);
            BranchIdNo.setVisible(false);
            jLabel5.setVisible(false);
            cardno.setVisible(false);
            jLabel9.setVisible(false);
            String bid=BookId.getText();
            flag=1;
        }

        else if("Authors".equals(name))
        {
            //JOptionPane.showMessageDialog(null,"Enter Book_ID and AuthorName");
            AuthorName.setVisible(true);
            BookId.setVisible(true);
            jLabel4.setVisible(true);
            jLabel2.setVisible(true);
            BranchIdNo.setVisible(false);
            jLabel5.setVisible(false);
            cardno.setVisible(false);
            jLabel9.setVisible(false);
            String bid=BookId.getText();
            String an=AuthorName.getText();
            flag=2;
        }
        else if("LibraryBranch".equals(name))
        {
            //JOptionPane.showMessageDialog(null,"Enter Branch_ID,Branch_name and Address");
            BranchIdNo.setVisible(true);
            jLabel5.setVisible(true);
            BookId.setVisible(false);
            AuthorName.setVisible(false);
            jLabel2.setVisible(false);
            jLabel4.setVisible(false);
            jLabel2.setVisible(false);
            cardno.setVisible(false);
            jLabel9.setVisible(false);
            String bid=BranchIdNo.getText();
            flag=3;
        }
        else if("BookCopies".equals(name))
        {
            //JOptionPane.showMessageDialog(null,"Enter Book_ID,Branch_ID and No.of Copies");
            BranchIdNo.setVisible(true);
            BookId.setVisible(true);
            jLabel2.setVisible(true);
            jLabel5.setVisible(true);
            AuthorName.setVisible(false);
            jLabel4.setVisible(false);
            cardno.setVisible(false);
            jLabel9.setVisible(false);
            String bid=BranchIdNo.getText();
            String bkid=BookId.getText();
            flag=4;
        }
        else if("Membership".equals(name))
        {
            //JOptionPane.showMessageDialog(null,"Enter Cardnumber,fname,lname,address and phone");
            cardno.setVisible(true);
            jLabel9.setVisible(true);
            jLabel1.setVisible(true);
            jLabel2.setVisible(true);
            BranchIdNo.setVisible(false);
            BookId.setVisible(false);
            jLabel2.setVisible(false);
            jLabel5.setVisible(false);
            AuthorName.setVisible(false);
            jLabel4.setVisible(false);
            String bid=BranchIdNo.getText();
            String bkid=BookId.getText();
            flag=4;
        }


    }//GEN-LAST:event_okActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new delete().setVisible(true);
            }
        });
    }
int flag=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AuthorName;
    private javax.swing.JButton Back;
    private javax.swing.JTextField BookId;
    private javax.swing.JTextField BranchIdNo;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField cardno;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
}
