/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package libraryapp;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static libraryapp.DB_Connection.conn;

/**
 *
 * @author Shravya
 */
public class insert extends javax.swing.JFrame {

    /**
     * Creates new form insert
     */
    public insert() {
        initComponents();
        jLabel2.setVisible(false);
        BookId.setVisible(false);
        jLabel3.setVisible(false);
        Title.setVisible(false);
        jLabel4.setVisible(false);
        AuthorName.setVisible(false);
        jLabel5.setVisible(false);
        BranchIdNo.setVisible(false);
        jLabel6.setVisible(false);
        BrName.setVisible(false);
        jLabel7.setVisible(false);
        BrAddress.setVisible(false);
        jLabel8.setVisible(false);
        TnoC.setVisible(false);
                
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        BookId = new javax.swing.JTextField();
        Title = new javax.swing.JTextField();
        AuthorName = new javax.swing.JTextField();
        BranchIdNo = new javax.swing.JTextField();
        BrName = new javax.swing.JTextField();
        BrAddress = new javax.swing.JTextField();
        TnoC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Book", "Authors", "LibraryBranch", "BookCopies" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("SELECT ANY OPTION");

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        BookId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookIdActionPerformed(evt);
            }
        });

        BrName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Book_id");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Title");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Author Name");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Branch_id");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Branch Name");

        jLabel7.setText("Address");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Number of copies");

        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Reset.setText("RESET");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(BranchIdNo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(72, 72, 72)
                                                .addComponent(jLabel6))
                                            .addComponent(AuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BookId, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(81, 81, 81)
                                                .addComponent(jLabel3)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Reset)
                                        .addGap(76, 76, 76)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Back)
                                            .addComponent(BrName, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BrAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(206, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TnoC, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(Submit)
                .addGap(354, 863, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BookId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(AuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BranchIdNo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BrName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(BrAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(jLabel8))
                    .addComponent(TnoC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit)
                    .addComponent(Reset)
                    .addComponent(Back))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        
		
		String name=jComboBox1.getSelectedItem().toString();
                
                if("".equals(name))
                {
                JOptionPane.showMessageDialog(null,"Please select any option");
                }
                
                else if("Book".equals(name))
                {
                //JOptionPane.showMessageDialog(null,"Enter Book_ID and Title");   
                BookId.setVisible(true);
                Title.setVisible(true);
                jLabel2.setVisible(true);
                jLabel3.setVisible(true);
                AuthorName.setVisible(false);
                jLabel4.setVisible(false);
                BrName.setVisible(false);
                BrAddress.setVisible(false);
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
                BranchIdNo.setVisible(false);
                TnoC.setVisible(false);
                jLabel5.setVisible(false);
                jLabel8.setVisible(false);
                String bid=BookId.getText();
                String t=Title.getText();
                flag=1;
                }
                
                else if("Authors".equals(name))
                {
                //JOptionPane.showMessageDialog(null,"Enter Book_ID and AuthorName");   
                AuthorName.setVisible(true);
                BookId.setVisible(true);
                jLabel4.setVisible(true);
                jLabel2.setVisible(true);
                Title.setVisible(false);
                jLabel3.setVisible(false);
                BrName.setVisible(false);
                BrAddress.setVisible(false);
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
                BranchIdNo.setVisible(false);
                TnoC.setVisible(false);
                jLabel5.setVisible(false);
                jLabel8.setVisible(false);
                String bid=BookId.getText();
                String an=AuthorName.getText();
                flag=2;
                }
                else if("LibraryBranch".equals(name))
                {
                //JOptionPane.showMessageDialog(null,"Enter Branch_ID,Branch_name and Address");   
                BranchIdNo.setVisible(true);
                BrName.setVisible(true);
                BrAddress.setVisible(true);
                jLabel6.setVisible(true);
                jLabel7.setVisible(true);
                jLabel5.setVisible(true);
                 
                BookId.setVisible(false);
                AuthorName.setVisible(false);
                jLabel3.setVisible(false);
                jLabel2.setVisible(false);
                jLabel4.setVisible(false);
                jLabel8.setVisible(false);
                TnoC.setVisible(false);
                jLabel2.setVisible(false);
                jLabel8.setVisible(false);
                String bid=BranchIdNo.getText();
                String bn=BrName.getText();
                String adr=BrAddress.getText();
                flag=3;
                }
                else if("BookCopies".equals(name))
                {
                //JOptionPane.showMessageDialog(null,"Enter Book_ID,Branch_ID and No.of Copies");   
                BranchIdNo.setVisible(true);
                BookId.setVisible(true);
                TnoC.setVisible(true);
                jLabel2.setVisible(true);
                jLabel5.setVisible(true);
                jLabel8.setVisible(true);
                Title.setVisible(false);
                jLabel3.setVisible(false);
                AuthorName.setVisible(false);
                jLabel4.setVisible(false);
                BrName.setVisible(false);
                BrAddress.setVisible(false);
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);
                String bid=BranchIdNo.getText();
                String bkid=BookId.getText();
                String noc=TnoC.getText();
                flag=4;
                }
                        
    }//GEN-LAST:event_okActionPerformed

    private void BookIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookIdActionPerformed

    private void BrNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BrNameActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
                try
		{
		// Create a connection to the local MySQL server, with the "world" database selected.
		conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/librarynew?user=root&password=shravya92");
		// Create a SQL statement object and execute the query.
		Statement stmt = conn.createStatement();
                String name=jComboBox1.getSelectedItem().toString();
                switch(flag)
                {
                    case 0:
                        JOptionPane.showMessageDialog(null,"Please choose a option"); 
                    case 1:
                        String bid=BookId.getText();
                        String t=Title.getText();
                        String add= "insert into book values('"+bid+"','"+t+"');";  
                        stmt.executeUpdate(add);
                        JOptionPane.showMessageDialog(null,"Succesfull");
                        BookId.setText("");
                        Title.setText("");
                        jComboBox1.setSelectedIndex(0);
                        BookId.setVisible(false);
                        Title.setVisible(false);
                        jLabel2.setVisible(false);
                        jLabel3.setVisible(false);
                        break;
                    case 2:
                         String bid1=BookId.getText();
                         String an1=AuthorName.getText();
                         String add1= "insert into Book_Authors values('"+bid1+"','"+an1+"');";
                         stmt.executeUpdate(add1);
                        JOptionPane.showMessageDialog(null,"Succesfull");
                        BookId.setText("");
                        AuthorName.setText("");
                        jComboBox1.setSelectedIndex(0);
                        BookId.setVisible(false);
                        AuthorName.setVisible(false);
                        jLabel2.setVisible(false);
                        jLabel4.setVisible(false);
                        break;
                    case 3:
                        String bid2=BranchIdNo.getText();
                        int b=Integer.parseInt(bid2);
                        String bn2=BrName.getText();
                        String adr2=BrAddress.getText();
                        String add2= "insert into Library_Branch values("+b+",'"+bn2+"','"+adr2+"');";
                        stmt.executeUpdate(add2);
                        JOptionPane.showMessageDialog(null,"Succesfull");
                        BranchIdNo.setText("");
                        BrName.setText("");
                        BrAddress.setText("");
                        jComboBox1.setSelectedIndex(0);
                        BranchIdNo.setVisible(false);
                        BrName.setVisible(false);
                        BrAddress.setVisible(false);
                        jLabel6.setVisible(false);
                        jLabel7.setVisible(false);
                        jLabel8.setVisible(false);
                        break;
                    case 4:
                        String bid3=BranchIdNo.getText();
                        int b1=Integer.parseInt(bid3);
                        String bkid3=BookId.getText();
                        String noc=TnoC.getText();
                        String add3= "insert into book_copies values('"+bkid3+"',"+b1+",'"+noc+"');";
                        stmt.executeUpdate(add3);
                        JOptionPane.showMessageDialog(null,"Succesfull");
                        BranchIdNo.setText("");
                        BookId.setText("");
                        TnoC.setText("");
                        jComboBox1.setSelectedIndex(0);
                        BranchIdNo.setVisible(false);
                        BookId.setVisible(false);
                        TnoC.setVisible(false);
                        jLabel2.setVisible(false);
                        jLabel5.setVisible(false);
                        jLabel8.setVisible(false);
                        break;
                }
                conn.close();
                }
                catch(SQLException ex)
		{
		JOptionPane.showMessageDialog(null,ex);
		}
    }//GEN-LAST:event_SubmitActionPerformed
public void close()
{
WindowEvent winclosingevent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclosingevent);
}
    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        close();
        HomePage hp=new HomePage();
        hp.setVisible(true);
        
    }//GEN-LAST:event_BackActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        switch(flag)
        {
            case 1:
                 BookId.setText("");
                 Title.setText("");
            case 2:
                BookId.setText("");
                AuthorName.setText("");
            case 3:
                BranchIdNo.setText("");
                BrName.setText("");
                BrAddress.setText("");
            case 4:
                BranchIdNo.setText("");
                BookId.setText("");
                TnoC.setText("");
        }
    }//GEN-LAST:event_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insert().setVisible(true);
            }
        });
    }
    int flag=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AuthorName;
    private javax.swing.JButton Back;
    private javax.swing.JTextField BookId;
    private javax.swing.JTextField BrAddress;
    private javax.swing.JTextField BrName;
    private javax.swing.JTextField BranchIdNo;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField Title;
    private javax.swing.JTextField TnoC;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
}
