/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package libraryapp;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static libraryapp.DB_Connection.conn;

/**
 *
 * @author Shravya
 */
public class update extends javax.swing.JFrame {

    /**
     * Creates new form insert
     */
    public update() {
        initComponents();
        jLabel2.setVisible(false);
        bookid.setVisible(false);
        jLabel3.setVisible(false);
        title.setVisible(false);
        jLabel4.setVisible(false);
        author.setVisible(false);
        jLabel5.setVisible(false);
        branchid.setVisible(false);
        jLabel6.setVisible(false);
        brname.setVisible(false);
        jLabel7.setVisible(false);
        braddress.setVisible(false);
        jLabel8.setVisible(false);
        tnoc.setVisible(false);
        cardno.setVisible(false);
        fname.setVisible(false);
        lname.setVisible(false);
        boaddress.setVisible(false);
        phoneno.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        bookid = new javax.swing.JTextField();
        title = new javax.swing.JTextField();
        author = new javax.swing.JTextField();
        branchid = new javax.swing.JTextField();
        brname = new javax.swing.JTextField();
        braddress = new javax.swing.JTextField();
        tnoc = new javax.swing.JTextField();
        cardno = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        boaddress = new javax.swing.JTextField();
        phoneno = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        back = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Book", "BookAuthors", "LibraryBranch", "BookCopies", "Membership" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("SELECT ANY OPTION");

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        bookid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookidActionPerformed(evt);
            }
        });

        brname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnameActionPerformed(evt);
            }
        });

        phoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenoActionPerformed(evt);
            }
        });

        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });

        jLabel2.setText("Book_id");

        jLabel3.setText("Title");

        jLabel4.setText("Author Name");

        jLabel5.setText("Branch_id");

        jLabel6.setText("Branch Name");

        jLabel7.setText("Address");

        jLabel8.setText("Total number of Copies");

        jLabel9.setText("Card Number");

        jLabel10.setText("Fname");

        jLabel11.setText("Lname");

        jLabel12.setText("Address");

        jLabel13.setText("Phone Number");

        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(tnoc, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cardno, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(submit)
                                .addGap(115, 115, 115)
                                .addComponent(reset)))
                        .addGap(44, 44, 44)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(boaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(brname, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(bookid, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27)
                                                .addComponent(jLabel3))
                                            .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(branchid, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27)
                                                .addComponent(jLabel6))))
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(back)
                                            .addComponent(braddress, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(branchid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(brname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(braddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tnoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cardno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submit)
                            .addComponent(reset)
                            .addComponent(back))
                        .addContainerGap(72, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        String name=jComboBox1.getSelectedItem().toString();
                
                if("".equals(name))
                {
                JOptionPane.showMessageDialog(null,"Please select any option");
                }
                
                else if("Book".equals(name))
                {
                //JOptionPane.showMessageDialog(null,"Enter Book_ID and Title");   
                bookid.setVisible(true);
                title.setVisible(true);
                jLabel2.setVisible(true);
                jLabel3.setVisible(true);
                author.setVisible(false);
                jLabel4.setVisible(false);
                brname.setVisible(false);
                braddress.setVisible(false);
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
                branchid.setVisible(false);
                tnoc.setVisible(false);
                jLabel5.setVisible(false);
                jLabel8.setVisible(false);
                cardno.setVisible(false);
                fname.setVisible(false);
                lname.setVisible(false);
                boaddress.setVisible(false);
                phoneno.setVisible(false);
                jLabel9.setVisible(false);
                jLabel10.setVisible(false);
                jLabel11.setVisible(false);
                jLabel12.setVisible(false);
                jLabel13.setVisible(false);
                String bid=bookid.getText();
                String t=title.getText();
                flag=1;
                }
                
                else if("BookAuthors".equals(name))
                {
                //JOptionPane.showMessageDialog(null,"Enter Book_ID and AuthorName");   
                author.setVisible(true);
                bookid.setVisible(true);
                jLabel4.setVisible(true);
                jLabel2.setVisible(true);
                title.setVisible(false);
                jLabel3.setVisible(false);
                brname.setVisible(false);
                braddress.setVisible(false);
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);
                jLabel8.setVisible(false);
                branchid.setVisible(false);
                tnoc.setVisible(false);
                jLabel5.setVisible(false);
                jLabel8.setVisible(false);
                cardno.setVisible(false);
                fname.setVisible(false);
                lname.setVisible(false);
                boaddress.setVisible(false);
                phoneno.setVisible(false);
                jLabel9.setVisible(false);
                jLabel10.setVisible(false);
                jLabel11.setVisible(false);
                jLabel12.setVisible(false);
                jLabel13.setVisible(false);
                String bid=bookid.getText();
                String an=author.getText();
                flag=2;
                }
                else if("LibraryBranch".equals(name))
                {
                //JOptionPane.showMessageDialog(null,"Enter Branch_ID,Branch_name and Address");   
                branchid.setVisible(true);
                brname.setVisible(true);
                braddress.setVisible(true);
                jLabel6.setVisible(true);
                jLabel7.setVisible(true);
                jLabel5.setVisible(true);
                title.setVisible(false);
                bookid.setVisible(false);
                author.setVisible(false);
                jLabel3.setVisible(false);
                jLabel2.setVisible(false);
                jLabel4.setVisible(false);
                jLabel8.setVisible(false);
                tnoc.setVisible(false);
                jLabel2.setVisible(false);
                jLabel8.setVisible(false);
                cardno.setVisible(false);
                fname.setVisible(false);
                lname.setVisible(false);
                boaddress.setVisible(false);
                phoneno.setVisible(false);
                jLabel9.setVisible(false);
                jLabel10.setVisible(false);
                jLabel11.setVisible(false);
                jLabel12.setVisible(false);
                jLabel13.setVisible(false);
                String bid=branchid.getText();
                String bn=brname.getText();
                String adr=braddress.getText();
                flag=3;
                }
                else if("BookCopies".equals(name))
                {
                //JOptionPane.showMessageDialog(null,"Enter Book_ID,Branch_ID and No.of Copies");   
                branchid.setVisible(true);
                bookid.setVisible(true);
                tnoc.setVisible(true);
                jLabel2.setVisible(true);
                jLabel5.setVisible(true);
                jLabel8.setVisible(true);
                title.setVisible(false);
                jLabel3.setVisible(false);
                author.setVisible(false);
                jLabel4.setVisible(false);
                brname.setVisible(false);
                braddress.setVisible(false);
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);
                cardno.setVisible(false);
                fname.setVisible(false);
                lname.setVisible(false);
                boaddress.setVisible(false);
                phoneno.setVisible(false);
                jLabel9.setVisible(false);
                jLabel10.setVisible(false);
                jLabel11.setVisible(false);
                jLabel12.setVisible(false);
                jLabel13.setVisible(false);
                String bid=branchid.getText();
                String bkid=bookid.getText();
                String noc=tnoc.getText();
                flag=4;
                }
                else if("Membership".equals(name))
                {
                //JOptionPane.showMessageDialog(null,"Enter Book_ID,Branch_ID and No.of Copies");   
                cardno.setVisible(true);
                fname.setVisible(true);
                lname.setVisible(true);
                boaddress.setVisible(true);
                phoneno.setVisible(true);
                jLabel9.setVisible(true);
                jLabel10.setVisible(true);
                jLabel11.setVisible(true);
                jLabel12.setVisible(true);
                jLabel13.setVisible(true);
                bookid.setVisible(false);
                branchid.setVisible(false);
                tnoc.setVisible(false);
                title.setVisible(false);
                jLabel2.setVisible(false);
                jLabel5.setVisible(false);
                jLabel8.setVisible(false);
                jLabel3.setVisible(false);
                author.setVisible(false);
                jLabel4.setVisible(false);
                brname.setVisible(false);
                braddress.setVisible(false);
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);
                jLabel2.setVisible(false);
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                String cno=cardno.getText();
                String fn=fname.getText();
                String ln=lname.getText();
                String bod=boaddress.getText();
                String phn=phoneno.getText();
                flag=5;
                }
    }//GEN-LAST:event_okActionPerformed

    private void bookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookidActionPerformed

    private void brnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brnameActionPerformed

    private void phonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenoActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        switch(flag)
        {
            case 1:
                 bookid.setText("");
                 title.setText("");
            case 2:
                bookid.setText("");
                author.setText("");
            case 3:
                branchid.setText("");
                brname.setText("");
                braddress.setText("");
            case 4:
                branchid.setText("");
                bookid.setText("");
                tnoc.setText("");
            case 5:
                cardno.setText("");
                fname.setText("");
                lname.setText("");
                boaddress.setText("");
                phoneno.setText("");
        }
        
    }//GEN-LAST:event_resetActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
         try
		{
		// Create a connection to the local MySQL server, with the "world" database selected.
		conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/librarynew?user=root&password=shravya92");
		// Create a SQL statement object and execute the query.
		Statement stmt = conn.createStatement();
                String name=jComboBox1.getSelectedItem().toString();
                switch(flag)
                {
                    case 0:
                        JOptionPane.showMessageDialog(null,"Please choose a option"); 
                    case 1:
                        String bid=bookid.getText();
                        String t=title.getText();
                        String add= "update  book set Book_id='"+bid+"',Title='"+t+"';";  
                        stmt.executeUpdate(add);
                        JOptionPane.showMessageDialog(null,"Succesfull");
                        bookid.setText("");
                        title.setText("");
                        jComboBox1.setSelectedIndex(0);
                        bookid.setVisible(false);
                        title.setVisible(false);
                        jLabel2.setVisible(false);
                        jLabel3.setVisible(false);
                        break;
                    case 2:
                         String bid1=bookid.getText();
                         String an1=author.getText();
                         String add1= "update Book_Authors set book_id='"+bid1+"',Author_name='"+an1+"';";
                         stmt.executeUpdate(add1);
                        JOptionPane.showMessageDialog(null,"Succesfull");
                        bookid.setText("");
                        author.setText("");
                        jComboBox1.setSelectedIndex(0);
                        bookid.setVisible(false);
                        author.setVisible(false);
                        jLabel2.setVisible(false);
                        jLabel4.setVisible(false);
                        break;
                    case 3:
                        String bid2=branchid.getText();
                        int b=Integer.parseInt(bid2);
                        String bn2=brname.getText();
                        String adr2=braddress.getText();
                        String add2= "update Library_Branch set branch_id="+b+",branch_name='"+bn2+"',Address='"+adr2+"';";
                        stmt.executeUpdate(add2);
                        JOptionPane.showMessageDialog(null,"Succesfull");
                        branchid.setText("");
                        brname.setText("");
                        braddress.setText("");
                        jComboBox1.setSelectedIndex(0);
                        branchid.setVisible(false);
                        brname.setVisible(false);
                        braddress.setVisible(false);
                        jLabel6.setVisible(false);
                        jLabel7.setVisible(false);
                        jLabel8.setVisible(false);
                        break;
                    case 4:
                        String bid3=branchid.getText();
                        int b1=Integer.parseInt(bid3);
                        String bkid3=bookid.getText();
                        String noc=tnoc.getText();
                        String add3= "update Book_Copies set book_id='"+bkid3+"',branch_id="+b1+",noc='"+noc+"';";
                        stmt.executeUpdate(add3);
                        JOptionPane.showMessageDialog(null,"Succesfull");
                        branchid.setText("");
                        bookid.setText("");
                        tnoc.setText("");
                        jComboBox1.setSelectedIndex(0);
                        branchid.setVisible(false);
                        bookid.setVisible(false);
                        tnoc.setVisible(false);
                        jLabel2.setVisible(false);
                        jLabel5.setVisible(false);
                        jLabel8.setVisible(false);
                        break;
                        
                    case 5:
                        String cno=cardno.getText();
                        String fn=fname.getText();
                        String ln=lname.getText();
                        String boadr=boaddress.getText();
                        String phn=phoneno.getText();
                        String add4= "update  Borrower card_no='"+cno+"',fname='"+fn+"',lname='"+ln+"',Address='"+boadr+"',Phone='"+phn+"';";
                        stmt.executeUpdate(add4);
                        JOptionPane.showMessageDialog(null,"Succesfull");
                        cardno.setText("");
                        fname.setText("");
                        lname.setText("");
                        boaddress.setText("");
                        phoneno.setText("");
                        jComboBox1.setSelectedIndex(0);
                        cardno.setVisible(false);
                        fname.setVisible(false);
                        lname.setVisible(false);
                        boaddress.setVisible(false);
                        phoneno.setVisible(false);
                        jLabel9.setVisible(false);
                        jLabel10.setVisible(false);
                        jLabel11.setVisible(false);
                        jLabel12.setVisible(false);
                        jLabel13.setVisible(false);
                        break;
                }
                conn.close();
                }
                catch(SQLException ex)
		{
		JOptionPane.showMessageDialog(null,ex);
		}
    }//GEN-LAST:event_submitActionPerformed
public void close()
{
WindowEvent winclosingevent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclosingevent);
}
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        close();
        HomePage hp=new HomePage();
        hp.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update().setVisible(true);
            }
        });
    }
    int flag;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField author;
    private javax.swing.JButton back;
    private javax.swing.JTextField boaddress;
    private javax.swing.JTextField bookid;
    private javax.swing.JTextField braddress;
    private javax.swing.JTextField branchid;
    private javax.swing.JTextField brname;
    private javax.swing.JTextField cardno;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lname;
    private javax.swing.JButton ok;
    private javax.swing.JTextField phoneno;
    private javax.swing.JButton reset;
    private javax.swing.JButton submit;
    private javax.swing.JTextField title;
    private javax.swing.JTextField tnoc;
    // End of variables declaration//GEN-END:variables
}
